### ISSUE TITLE
GetTradesAsync not working

### ISSUE THREAD

**Issue by mscheetz** [dougdellolio/coinbasepro-csharp#134]
As the title says. When i run, it keeps returning that i've exceeded my request limit.

**Comment by dougdellolio** [comment]
hi @mscheetz can you provide the exact call you are making that is causing this error?

**Comment by chrisw000** [comment]
GetTradesAsync can throw this error for the same sort of reason the Historic Candles can... and infact any of the paged result sets can (the ones that call into `SendHttpRequestMessagePagedAsync`

https://docs.gdax.com/#rate-limits says 3 API calls per second, per IP

When it loops and re-calls the API for next page, it's quite possible to hit the rate limit.

**Comment by dougdellolio** [comment]
yup that is definitely it. might need to request fewer pages

**Comment by guanm326** [comment]
So just to confirm, GetOrderByIdAsync is not paged so I can make as many calls as I want? What about PlaceLimitOrderAsync? Is there a rate-limit on the number of order placement/order cancellation per second?

If GetOrderByIdAsync is not rate limited, one could just focus on maintaining up to date their order status. From there you can determine when your orders will be filled and create internal trade events. To make sure records match, you can then create a scheduled request to make sure last 10 trades matches with what the Exchange has.

I hope I am not missing anything. Love to hear how others are handling this.

**Comment by dougdellolio** [comment]
All requests are rate limited. You can see those limits here: https://docs.gdax.com/#rate-limits

The  requests that have a paged response(like GetTradesAsync) will make multiple subsequent calls to get all of the pages. So if you are asking for too many pages it will complain. Since you didn’t provide in your example call above it’s going to try and get all pages (probably many) which is why I suspect GDAX is complainingl. You can try passing in a limit and number of pages. Here’s an example in the readme: https://github.com/dougdellolio/gdax-csharp#getting-account-history-paged-response.
