### ISSUE TITLE
multiple order statuses

### ISSUE THREAD

**Issue by bwjunkie** [dougdellolio/coinbasepro-csharp#156]
I don't see an implementation for multiple order status:
To specify multiple statuses, use the status query argument multiple times: 
/orders?status=done&status=pending.

**Comment by dougdellolio** [comment]
The ability to request multiple order statuses doesn't exist in this library currently. You can however pass in an order status of `All` to retrieve all orders of all types and then filter on the status within your program. Feel free to take a shot at implementing it here otherwise I can pick this up soon.
