### ISSUE TITLE
All Trade History

### ISSUE THREAD

**Issue by ryanfalzon** [dougdellolio/coinbasepro-csharp#165]
Am I correct to say that the way the wrapper has been written, there is no way to get a list of trades greater than the limit which is a 100?

**Comment by dougdellolio** [comment]
@ryanfalzon 

The maximum limit of 100 is set by Coinbase here: https://docs.pro.coinbase.com/#pagination. This means that per page you can only get up to 100 results. You can still pass in 0 (the default) for the number of pages which will return all pages.

If you are referring to getting a rate limit error for requesting all pages then yes that is due to how the requests are handled in this library. If you want you can pass in your own implementation of `IHttpClient` to add a delay to prevent the rate limits from being exceeded (from readme: https://github.com/dougdellolio/coinbasepro-csharp#overriding-the-httpclient-behavior). An example of a rate limited httpclient from another user is here: https://github.com/chrisw000/gdax-csharp/commit/74f1503451ae1055b810f53a034ceb1bbeef32a0#diff-c9ba790961311e6999a6a22e87b9713c

**Comment by ryanfalzon** [comment]
So if for instance I have 500 transactions, how would I go about getting all 500? Normally, exchanges would  have an offset value meaning that would first get a 100 transactions with an offset of 0, then I would get a 100 transaction with an offset of 100, then I would get a 100 transactions with an offset of 200 etc. Can this be done using this wrapper?

**Comment by dougdellolio** [comment]
The library takes care of requesting with the offsets for you. For your example if you know you have 500 and leave the limit and page number as default then it will return 5 pages with 100 transactions in it. like this: `coinbaseProClient.FillsService.GetFillsByProductIdAsync(ProductType.BtcUsd)` This will make 5 network requests to get all 500 transactions and return into a list for you.

Alternatively you can request fewer pages with fewer items per page:
`coinbaseProClient.FillsService.GetFillsByProductIdAsync(ProductType.BtcUsd, 5, 5)` . This will return you 5 pages with 5 items in it which is the first 25 transactions. (this is a dumb example but realistically you could just ask for 1 page with 25 items in it). 

let me know if this doesn't answer your question or is still unclear.

**Comment by ryanfalzon** [comment]
Thank you very much for you time. One last question, what is the class TimeSpanEmaphore.cs?

**Comment by dougdellolio** [comment]
@ryanfalzon no worries. you can see the implementation of that class here: https://github.com/chrisw000/gdax-csharp/commit/0deb79e793ce1775b335265ef7bee87fefad18f9.
