### ISSUE TITLE
Add releases to nuget

### ISSUE THREAD

**Issue by LeonardoX77** [dougdellolio/coinbasepro-csharp#167]
Hi
Please, add to nuget every release, so we don't have to clone master branch, pull, compile and so ...

Thanks

**Comment by dougdellolio** [comment]
@LeonardoX77 hey, every release here is also released to nuget. The latest package you will find is v1.0.23. let me know if you are referring to something different

**Comment by LeonardoX77** [comment]
My apologies. I didn't found any reference in README.md and nuget.org searching "coinbasepro" or "coinbasepro-csharp", so I supposed it wasn't published. Could you please post nuget url and update README.md to avoid others make same mistake?
Thanks
Regards

**Comment by dougdellolio** [comment]
the name is still under GDAX since nuget won't allow me to change the name or ID without losing all version history 😞. The readme already contains a badge which displays latest version and links to the nuget page: 
![capture](https://user-images.githubusercontent.com/4141717/47624983-3920de00-daf8-11e8-9ef3-f9d1fa48f3b0.PNG)

will close for now
