### ISSUE TITLE
A call to SSPI failed, the function is not supported.

### ISSUE THREAD

**Issue by Lumaswell** [dougdellolio/coinbasepro-csharp#225]
I took a break of a few months from my code, when I came back and updated my packages I started getting an error I've not seen before.

The following exception is thrown.
1) A call to SSPI failed, see inner exception.
The inner exception is then:
2) The function requested is not supported

Since I made no changes to my code and this popped up, and it's part of the websocket code I'm reasonably certain it's not something I did.

**Comment by dougdellolio** [comment]
hey @Lumaswell. I think this is actually a problem on Coinbases side. They are reporting connectivity issues and partially degraded services. I will verify again when it's back up to make sure it's not a code issue but nothing has changed in the websocket code recently.

Their tweet here as of 8:49 PM EST https://twitter.com/CoinbaseSupport/status/1259284459838267392
and their status here: https://status.pro.coinbase.com/

**Comment by dougdellolio** [comment]
@Lumaswell this has stumped me a bit and not sure at what point or even why this became an issue. After doing some searching it seems to be potentially related to .NET and/or the OS. When the library creates a new instance of the Websocket, no SSL protocol is explicitly set (following Microsoft's recommendation). The option `SslProtocols.None`, which is defaulted when the websocket is initialized, allows the operating system to choose the best protocol to use (https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls).

This isn't a problem when targetting .NET core but targetting 4.7.2 shows the issue. I have found that setting the SslProtocol seems to fix it but I am not 100% on this solution. .https://github.com/dougdellolio/coinbasepro-csharp/blob/fix/set-ssl-protocol/CoinbasePro/WebSocket/WebSocketFeed.cs#L20 . Would love to hear thoughts from anyone that is more familiar with this subject otherwise I will go ahead with the proposed fix.

**Comment by Lumaswell** [comment]
The only reference I found when I was originally thinking I'd screwed something up, was a changelog on  coinbase that showed they updated either the TLS or the SSL protocol.  Of course, I can't find this webpage now to link to you despite searching for the last 20 minutes.  I am using .net framework for my code, I'll have to make the switch in the near future.  Thanks for your hardwork on this.

**Comment by dougdellolio** [comment]
No worries. I have released the change. Please update to v1.0.36 and try it again. Feel free to re-open this if you are still seeing problems with it. thanks!
