### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by lploumen** [dougdellolio/coinbasepro-csharp#232]
Hi,
I am using the sandbox, I have a account with less than 1BTC. When trying to sell 3 BTC, I do not get any errors and it sell my whole BTC balance. On the website, when trying the same, I get the expected error 'insufficient funds'.
How can I get this error when using the API?
Thank you !

**Comment by dougdellolio** [comment]
Hi @lploumen ,

The sandbox account will use a different balance than your live account. It is typically a very large number. I just tried placing a market order for more than my sandbox account balance and I am receiving the error. 

![image](https://user-images.githubusercontent.com/4141717/84595273-f3c43800-ae24-11ea-9e7c-c02ad6b249c1.png)

Trying to sell 221,851 throws this:

![image](https://user-images.githubusercontent.com/4141717/84595289-0b032580-ae25-11ea-8f06-b29839d4eac2.png)

Let me know if you're still not seeing this.

**Comment by lploumen** [comment]
Hi!
No I don't seem to get same result as you.
I have this balance:
![image](https://user-images.githubusercontent.com/11539944/84701128-ac3cc980-af54-11ea-8223-dfbce16ad535.png)

Now I try to buy market 4 BTC (which  should not be possible) , and I get that in the logs:
![image](https://user-images.githubusercontent.com/11539944/84701252-ed34de00-af54-11ea-9d92-85a11aacd19c.png)

See the remainingsize...
But I don't get any errors.

Best regards,

**Comment by dougdellolio** [comment]
@lploumen it looks like you aren't seeing the exception because you are getting part of your order filled. If you notice the remaining size is ~3.82142768 of the 4 BTC. If you run the place order again, you will get the error because there are truly no funds available. 

I am not 100% sure of the logic here because its not documented but I am seeing what you are seeing on "Buy" only orders. However, when placing "Sell" orders it seems to be all or nothing which is what I had tried in my first comment above.

Lastly, I noticed for "Buy" orders, if you set the `MarketOrderAmountType` to `Funds` (the optional argument when placing market order), it will not do any partial buys and should fail on the first attempt.
