### ISSUE TITLE
Does this library work with Coinbase Prime?

### ISSUE THREAD

**Issue by bondocel11** [dougdellolio/coinbasepro-csharp#239]

**Comment by dougdellolio** [comment]
@bondocel11 this library will not work with Coinbase Prime currently because the URLs all point to Coinbase Pro.  (https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Shared/ApiUris.cs#L9). I believe changing the URLs  could work since the APIs all look the same but I would have to figure out a way to get an account to test this theory.
