### ISSUE TITLE
Example for automatically sending sell order after filled buy order

### ISSUE THREAD

**Issue by jamesboyer** [dougdellolio/coinbasepro-csharp#263]
I was wondering what would be the recommended way to send a limit sell order after placing and filling a buy order. I have similar to the following, however I never get a Done matching my buyId so I can place a sell limit order. Is there a different web socket event I should be listening to?

```c#
var authenticator = new Authenticator(GetApiKey(), GetApiSecret(), GetPassphrase());
var coinbaseConnection = new CoinbasePro.CoinbaseProClient(authenticator);

var buyId = Guid.NewGuid();
void WebSocket_OnDoneReceived(object sender, WebfeedEventArgs<Done> e)
{
    if (!e.LastOrder.OrderId.Equals(buyId)) {
      return;
    }
    coinbaseConnection.OrdersService.PlaceLimitOrderAsync(
        OrderSide.Sell,
        bid.ProductType,
        bidSize,
        sellPrice,
        clientOid: sellOrderId);
}
coinbaseConnection.WebSocket.OnDoneReceived += WebSocket_OnDoneReceived;

var buyResult = await coinbaseConnection
    .OrdersService
    .PlaceLimitOrderAsync(
      OrderSide.Buy,
      bid.ProductType,
      bidSize,
      bidPrice,
      timeInForce: TimeInForce.Fok,
      postOnly: false,
      clientOid: buyOrderId);
```

**Comment by dougdellolio** [comment]
hey @jamesboyer,

A few things here:

The client_oid that you are passing in when placing the order is _different_ than the `OrderId` on `LastOrder` so the match you are doing won't work. The correct way to do this would be to use the `id` property returned from your `buyResult`  as the match in your `OnDoneRecieved` instead of the buyId. Something like this:

```csharp
var tradeId = buyResult.Id;

void WebSocket_OnDoneReceived(object sender, WebfeedEventArgs<Done> e)
{
    if (e.LastOrder.OrderId == tradeId)
    {
        Console.WriteLine("ORDER HAS BEEN FILLED");
    }
}
``` 
The client_oid will only be available on the public feed for a `received` message and according to the docs will NOT be used after the `recieved` message is sent. But if you want to be able to see your trade on the public feed you'll have to subscribe to `OnReceivedReceived` from the websocket. For example:

```csharp
coinbaseConnection.WebSocket.OnReceivedReceived += WebSocket_OnReceivedReceived;

void WebSocket_OnReceivedReceived(object sender, WebfeedEventArgs<Received> e)
{
    if (e.LastOrder.ClientOid == buyId)
    {
        Console.WriteLine("We match!");
    }
}
```
hope this helps. Let me know if you are still running into any issues or it's not clear.

**Comment by jamesboyer** [comment]
Makes sense. Only downside is that the `WebSocket_OnDoneReceived` could get handled prior to me setting `tradeId`. Will have to figure out a way around that but shouldn't be too hard. Important thing is at least I do have the right event. Thanks for the help.
