### ISSUE TITLE
Deposit details missed fields

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#269]
- Current version of CoinbasePro.Services.Deposits.Models.Details contains prop SentToAddress, but must not.
Prop crypto_address should be implemented instead: https://docs.pro.coinbase.com/#deposits
- coinbase_transaction_id is also missed
- CoinbasePaymentMethodId is useless for deposits, it is for withdrawals

**Comment by dougdellolio** [comment]
hi @ahilis changes have been made here:https://github.com/dougdellolio/coinbasepro-csharp/commit/e692de7f428f10f375a308f288bea68f34c953b3

for these requests it might be best if you fork the project and create PRs with the changes. May be easier that way as it seems you are finding some of the models have changed since their initial implementation. thx
